"""
teps_generator.py
------------------
Groq API (llama-3.1-8b-instant)를 사용해 매일 TEPS 포스트를 생성하고
_posts/ 폴더에 Jekyll 마크다운 파일로 저장합니다.

단어 소스: 컨설텝스 뉴텝스 빈출 어휘 1차~58차 (총 1400+ 단어)
실행: python teps_generator.py
환경변수: GROQ_API_KEY
"""

import os
import sys
import random
from datetime import datetime, timezone, timedelta
from groq import Groq

# ── 설정 ──────────────────────────────────────────────────────────────────────
KST = timezone(timedelta(hours=9))
MODEL = "llama-3.1-8b-instant"
POSTS_DIR = "_posts"

# ── TEPS 빈출 어휘 (컨설텝스 뉴텝스 1차~40차) ────────────────────────────────
# 형식: (영어 단어, 한국어 의미, 품사)
TEPS_VOCABULARY = [
    # 1차
    ("public", "대중의, 대중", "형용사"),
    ("likely", "~할 것 같은", "형용사"),
    ("unlikely", "~할 것 같지 않은", "형용사"),
    ("available", "이용할 수 있는", "형용사"),
    ("species", "종", "명사"),
    ("offer", "제안하다", "동사"),
    ("local", "지역의", "형용사"),
    ("ancient", "고대의", "형용사"),
    ("major", "주요한", "형용사"),
    ("majority", "다수", "명사"),
    ("common", "일반적인, 공통의", "형용사"),
    ("announcement", "발표", "명사"),
    ("market", "시장", "명사"),
    ("rate", "속도, 비율", "명사"),
    ("current", "현재의, 흐름", "형용사"),
    ("provide", "제공하다", "동사"),
    ("policy", "정책", "명사"),
    ("decision", "결정", "명사"),
    ("receive", "받다", "동사"),
    ("novel", "새로운, 소설", "형용사"),
    # 2차
    ("means", "수단, 방법", "명사"),
    ("effective", "효과적인", "형용사"),
    ("performance", "공연, 성과", "명사"),
    ("benefits", "이익", "명사"),
    ("comprehension", "이해", "명사"),
    ("comprehensive", "포괄적인", "형용사"),
    ("avoid", "회피하다", "동사"),
    ("theory", "이론", "명사"),
    ("disease", "질병", "명사"),
    ("income", "수입", "명사"),
    ("staff", "직원", "명사"),
    ("original", "원래의, 독창적인", "형용사"),
    ("origin", "기원", "명사"),
    ("control", "지배, 지배하다", "명사"),
    ("choose", "선택하다", "동사"),
    ("matter", "문제, 중요하다", "명사"),
    ("contact", "연락, 연락하다", "명사"),
    ("decide", "결정하다", "동사"),
    ("industry", "산업", "명사"),
    ("growth", "성장", "명사"),
    # 3차
    ("practice", "연습, 관행", "명사"),
    ("value", "가치", "명사"),
    ("valuable", "소중한, 값비싼", "형용사"),
    ("environment", "환경", "명사"),
    ("environmental", "환경의", "형용사"),
    ("individual", "개인의", "형용사"),
    ("produce", "생산하다", "동사"),
    ("lack", "부족, 부족하다", "명사"),
    ("media", "매체", "명사"),
    ("impact", "충격, 영향", "명사"),
    ("criticism", "비판, 비평", "명사"),
    ("risk", "위험", "명사"),
    ("behavior", "행동", "명사"),
    ("improve", "개선하다", "동사"),
    ("resources", "자원", "명사"),
    ("eventually", "결국, 마침내", "부사"),
    ("construction", "건설, 공사", "명사"),
    ("influence", "영향", "명사"),
    # 4차
    ("toward", "~을 향하여", "전치사"),
    ("previous", "이전의", "형용사"),
    ("potential", "가능성이 있는", "형용사"),
    ("damage", "피해, 손상을 주다", "명사"),
    ("charge", "요금, 청구하다", "명사"),
    ("reduce", "줄이다", "동사"),
    ("responsible", "책임이 있는", "형용사"),
    ("responsibility", "책임", "명사"),
    ("particular", "특정한", "형용사"),
    ("particularly", "특히", "부사"),
    ("global", "세계적인, 전반적인", "형용사"),
    ("management", "경영", "명사"),
    ("amount", "양", "명사"),
    ("general", "일반적인", "형용사"),
    ("create", "창조하다", "동사"),
    ("allow", "허락하다", "동사"),
    ("request", "요청, 요청하다", "명사"),
    # 5차
    ("prevent", "예방하다", "동사"),
    ("security", "보안, 경비", "명사"),
    ("secure", "안심하는, 확보하다", "형용사"),
    ("fiction", "소설, 허구", "명사"),
    ("apply", "지원하다, 적용하다", "동사"),
    ("application", "지원서, 신청", "명사"),
    ("evidence", "증거", "명사"),
    ("purchase", "구입하다, 구매", "동사"),
    ("status", "신분, 지위", "명사"),
    ("budget", "예산", "명사"),
    ("annual", "연례의", "형용사"),
    ("complex", "복잡한", "형용사"),
    ("physical", "육체의", "형용사"),
    ("spread", "번식하다, 퍼지다", "동사"),
    ("officials", "공무원들", "명사"),
    ("proposal", "제안", "명사"),
    ("addition", "추가, 덧셈", "명사"),
    # 6차
    ("competition", "경쟁, 대회", "명사"),
    ("compete", "경쟁하다", "동사"),
    ("highly", "대단히, 매우", "부사"),
    ("depression", "우울증", "명사"),
    ("advice", "조언", "명사"),
    ("average", "평균의, 일반적인", "형용사"),
    ("material", "재료", "명사"),
    ("notice", "인식하다, 공고문", "동사"),
    ("weight", "체중", "명사"),
    ("labor", "노동, 근로", "명사"),
    ("property", "재산", "명사"),
    ("contract", "계약서, 수축하다", "명사"),
    ("deal", "거래, 다루다", "명사"),
    ("access", "접근, 접근하다", "명사"),
    ("nearly", "거의", "부사"),
    ("focus", "집중시키다, 주목", "동사"),
    ("exercise", "운동", "명사"),
    ("mental", "정신의", "형용사"),
    ("regular", "규칙적인", "형용사"),
    ("claim", "주장하다, 요구하다", "동사"),
    # 7차
    ("private", "사적인", "형용사"),
    ("privacy", "사생활", "명사"),
    ("insurance", "보험", "명사"),
    ("methods", "방법", "명사"),
    ("condition", "상태", "명사"),
    ("suggest", "제안하다", "동사"),
    ("rights", "권리", "명사"),
    ("prior", "사전의, 우선적인", "형용사"),
    ("priority", "우선 사항", "명사"),
    ("bill", "계산서, 요금", "명사"),
    ("fee", "수수료", "명사"),
    ("consumers", "소비자들", "명사"),
    ("attempt", "시도", "명사"),
    ("atmosphere", "대기, 분위기", "명사"),
    ("additional", "추가적인", "형용사"),
    ("especially", "특히", "부사"),
    ("specific", "구체적인", "형용사"),
    ("review", "검토, 비평", "명사"),
    ("remain", "남다, 남아 있다", "동사"),
    ("attend", "참석하다", "동사"),
    ("region", "지방", "명사"),
    ("climate", "기후, 분위기", "명사"),
    ("native", "태어난 곳의", "형용사"),
    # 8차
    ("election", "선거", "명사"),
    ("location", "장소", "명사"),
    ("organic", "유기농의", "형용사"),
    ("pressure", "압박, 압력", "명사"),
    ("significant", "중요한", "형용사"),
    ("necessary", "필요한", "형용사"),
    ("surface", "표면", "명사"),
    ("source", "원천", "명사"),
    ("range", "범위", "명사"),
    ("treatment", "치료, 대우", "명사"),
    ("demand", "요구, 요구하다", "명사"),
    ("relationship", "관계", "명사"),
    ("essential", "필수적인", "형용사"),
    ("approach", "다가가다, 접근법", "동사"),
    ("accept", "받아들이다", "동사"),
    ("population", "인구", "명사"),
    ("tend", "경향이 있다", "동사"),
    ("tendency", "경향", "명사"),
    ("maintain", "유지하다", "동사"),
    ("ensure", "보장하다", "동사"),
    # 9차
    ("participants", "참가자들", "명사"),
    ("participation", "참가", "명사"),
    ("experts", "전문가들", "명사"),
    ("definitely", "분명히", "부사"),
    ("encourage", "권장하다, 장려하다", "동사"),
    ("affordable", "감당할 수 있는", "형용사"),
    ("character", "성격, 특징", "명사"),
    ("characteristics", "특성들", "명사"),
    ("court", "법정", "명사"),
    ("submit", "제출하다, 항복하다", "동사"),
    ("civil", "시민의", "형용사"),
    ("supply", "공급, 공급하다", "명사"),
    ("assistance", "도움, 원조", "명사"),
    ("familiar", "친숙한", "형용사"),
    ("recommend", "추천하다", "동사"),
    ("race", "경주, 경쟁", "명사"),
    ("advanced", "상급의", "형용사"),
    ("stock", "주식", "명사"),
    # 10차
    ("legal", "법적인", "형용사"),
    ("variety", "여러 가지, 다양성", "명사"),
    ("fuel", "연료", "명사"),
    ("directly", "곧장, 똑바로", "부사"),
    ("seek", "찾다, 추구하다", "동사"),
    ("identify", "확인하다", "동사"),
    ("identity", "신원, 정체성", "명사"),
    ("response", "대답, 반응", "명사"),
    ("reputation", "명성, 평판", "명사"),
    ("appreciate", "인정하다, 고마워하다", "동사"),
    ("promote", "촉진하다, 승진시키다", "동사"),
    ("describe", "묘사하다", "동사"),
    ("chemical", "화학적인", "형용사"),
    ("raise", "들어올리다, 일으키다", "동사"),
    ("objective", "목표, 객관적인", "명사"),
    ("basis", "근거, 이유", "명사"),
    ("facilities", "시설들", "명사"),
    ("realize", "깨닫다", "동사"),
    ("central", "가장 중요한, 중앙의", "형용사"),
    # 11차
    ("former", "이전의", "형용사"),
    ("latter", "후자의", "형용사"),
    ("recall", "기억해 내다", "동사"),
    ("appointment", "약속, 임명", "명사"),
    ("electronics", "전자 공학", "명사"),
    ("affect", "영향을 미치다", "동사"),
    ("share", "공유하다, 몫", "동사"),
    ("analysis", "분석", "명사"),
    ("title", "제목", "명사"),
    ("board", "위원회, 탑승하다", "명사"),
    ("nevertheless", "그럼에도 불구하고", "부사"),
    ("campaign", "캠페인", "명사"),
    ("organization", "조직", "명사"),
    ("inform", "알리다", "동사"),
    ("immediately", "즉시", "부사"),
    ("abroad", "해외로", "부사"),
    ("structure", "구조, 조직하다", "명사"),
    ("genetic", "유전의", "형용사"),
    ("ultimately", "궁극적으로, 결국", "부사"),
    ("audience", "청중", "명사"),
    ("regarding", "~에 관하여", "전치사"),
    # 12차
    ("grand", "웅장한", "형용사"),
    ("beneficial", "유익한", "형용사"),
    ("debate", "토론, 논쟁", "명사"),
    ("equipment", "장비, 용품", "명사"),
    ("contain", "~이 들어 있다, 억누르다", "동사"),
    ("typically", "전형적으로", "부사"),
    ("primary", "주요한, 최초의", "형용사"),
    ("discovery", "발견", "명사"),
    ("degree", "도, 정도", "명사"),
    ("reach", "~에 이르다", "동사"),
    ("measures", "방안, 방법", "명사"),
    ("aware", "알고 있는", "형용사"),
    ("furthermore", "뿐만 아니라, 더욱이", "부사"),
    ("warning", "경고", "명사"),
    ("decline", "감소하다", "동사"),
    ("funding", "자금 조달", "명사"),
    ("formal", "격식을 차린, 공식적인", "형용사"),
    ("gain", "얻다, 이득", "동사"),
    ("corporate", "기업의", "형용사"),
    ("grade", "품질, 등급", "명사"),
    ("semester", "학기", "명사"),
    ("perform", "수행하다, 공연하다", "동사"),
    # 13차
    ("wonder", "궁금하다", "동사"),
    ("wander", "돌아다니다", "동사"),
    ("release", "풀어 주다", "동사"),
    ("minor", "작은", "형용사"),
    ("minority", "소수", "명사"),
    ("overall", "종합적인", "형용사"),
    ("planet", "행성", "명사"),
    ("contemporary", "동시대의, 현대의", "형용사"),
    ("remind", "상기시키다", "동사"),
    ("graduate", "졸업자, 졸업하다", "명사"),
    ("investment", "투자", "명사"),
    ("function", "기능", "명사"),
    ("otherwise", "그렇지 않으면", "부사"),
    ("separate", "분리된, 별개의", "형용사"),
    ("suffering", "고통", "명사"),
    ("contrast", "대조, 대비", "명사"),
    ("concept", "개념", "명사"),
    ("domestic", "국내의, 가정의", "형용사"),
    ("academic", "학업의", "형용사"),
    ("standard", "기준, 일반적인", "명사"),
    ("illness", "병", "명사"),
    ("desire", "욕구, 바라다", "명사"),
    # 14차
    ("exchange", "교환, 교환하다", "명사"),
    ("replace", "대신하다, 교체하다", "동사"),
    ("technical", "기술적인", "형용사"),
    ("consumption", "소비", "명사"),
    ("figure", "수치, 인물", "명사"),
    ("commercial", "상업의", "형용사"),
    ("employment", "고용", "명사"),
    ("alternative", "대안, 대체 가능한", "명사"),
    ("capacity", "수용력, 능력", "명사"),
    ("capable", "~을 할 수 있는, 유능한", "형용사"),
    ("firm", "회사, 딱딱한", "명사"),
    ("poverty", "가난, 부족", "명사"),
    ("furniture", "가구", "명사"),
    ("determine", "알아내다, 결정하다", "동사"),
    ("favorable", "유리한, 순조로운", "형용사"),
    ("estate", "사유지", "명사"),
    ("vehicle", "탈 것, 수단", "명사"),
    ("regulations", "규제", "명사"),
    ("advantage", "유리한 점, 장점", "명사"),
    ("obesity", "비만", "명사"),
    ("medicine", "의학, 의료", "명사"),
    ("severe", "극심한, 엄격한", "형용사"),
    # 15차
    ("operation", "수술, 작전", "명사"),
    ("agricultural", "농업의", "형용사"),
    ("license", "면허증", "명사"),
    ("intention", "의도, 목적", "명사"),
    ("distance", "거리", "명사"),
    ("distant", "먼", "형용사"),
    ("vision", "시야, 미래 비전", "명사"),
    ("exposure", "노출", "명사"),
    ("rare", "드문, 진귀한", "형용사"),
    ("genre", "장르", "명사"),
    ("parliament", "의회", "명사"),
    ("moral", "도의적인, 도덕상의", "형용사"),
    ("colleagues", "동료들", "명사"),
    ("transportation", "운송", "명사"),
    ("selection", "선발, 선정", "명사"),
    ("generation", "세대", "명사"),
    ("earn", "벌다, 얻다", "동사"),
    ("storage", "저장", "명사"),
    ("significance", "중요성, 의미", "명사"),
    ("entire", "전체의", "형용사"),
    ("accurate", "정밀한", "형용사"),
    ("efficient", "능률적인, 효율적인", "형용사"),
    ("moreover", "게다가", "부사"),
    ("profits", "수익, 이익", "명사"),
    # 16차
    ("trend", "동향, 추세", "명사"),
    ("bias", "편견", "명사"),
    ("conservative", "보수적인", "형용사"),
    ("donation", "기부", "명사"),
    ("independence", "자립, 독립", "명사"),
    ("strategies", "전략들", "명사"),
    ("target", "겨냥하다, 대상", "동사"),
    ("clearly", "분명히", "부사"),
    ("electric", "전기의", "형용사"),
    ("crisis", "위기", "명사"),
    ("diversity", "다양성", "명사"),
    ("diverse", "다양한", "형용사"),
    ("reservation", "예약, 의구심", "명사"),
    ("injuries", "부상", "명사"),
    ("innovative", "혁신적인", "형용사"),
    ("numerous", "수많은", "형용사"),
    ("confidence", "자신감, 신뢰", "명사"),
    ("achieve", "달성하다", "동사"),
    ("trial", "재판", "명사"),
    # 17차
    ("fear", "공포, 두려워하다", "명사"),
    ("factor", "요인", "명사"),
    ("tough", "힘든, 거친", "형용사"),
    ("household", "가정, 집안", "명사"),
    ("initial", "초기의, 처음의", "형용사"),
    ("district", "구역, 지역", "명사"),
    ("argue", "언쟁을 하다, 입증하다", "동사"),
    ("controversial", "논란이 많은", "형용사"),
    ("controversy", "논란", "명사"),
    ("representative", "대리인", "명사"),
    ("represent", "대변하다, 나타내다", "동사"),
    ("superior", "우수한, 상급자", "형용사"),
    ("ideal", "이상적인", "형용사"),
    ("procedure", "절차", "명사"),
    ("manufacturing", "제조업, 생산", "명사"),
    ("gender", "성별", "명사"),
    ("instructions", "지시", "명사"),
    ("housing", "주거시설", "명사"),
    ("display", "전시하다, 전시", "동사"),
    ("register", "등록하다", "동사"),
    ("pollution", "오염", "명사"),
    ("strict", "엄격한", "형용사"),
    ("violence", "폭력", "명사"),
    # 18차
    ("guidelines", "지침", "명사"),
    ("rely", "신뢰하다, 의지하다", "동사"),
    ("reliable", "믿을 수 있는", "형용사"),
    ("council", "의회, 위원회", "명사"),
    ("forecast", "예측", "명사"),
    ("scale", "규모", "명사"),
    ("permission", "승인, 허락", "명사"),
    ("exhibit", "전시회, 발휘하다", "명사"),
    ("editor", "편집자", "명사"),
    ("payment", "지불", "명사"),
    ("agency", "대리점", "명사"),
    ("mention", "언급하다, 언급", "동사"),
    ("obtain", "얻다", "동사"),
    ("productivity", "생산성", "명사"),
    ("theme", "주제", "명사"),
    ("dedicated", "전념하는", "형용사"),
    ("transfer", "이송하다, 옮기다", "동사"),
    ("committee", "위원회", "명사"),
    ("recognize", "알아보다, 승인하다", "동사"),
    ("retirement", "은퇴", "명사"),
    ("incident", "일, 사건", "명사"),
    ("radiation", "방사선", "명사"),
    ("faith", "믿음, 종교", "명사"),
    ("hardly", "거의~아니다", "부사"),
    ("doubt", "의심", "명사"),
    # 19차
    ("candidate", "후보", "명사"),
    ("recession", "경기침체, 후퇴", "명사"),
    ("lend", "빌려주다", "동사"),
    ("extremely", "극도로, 극히", "부사"),
    ("mobile", "이동하는, 기동성이 있는", "형용사"),
    ("critical", "비판적인, 중대한", "형용사"),
    ("threat", "협박", "명사"),
    ("aid", "지원, 도움, 돕다", "명사"),
    ("frequently", "자주, 흔히", "부사"),
    ("recipient", "받는 사람, 수취인", "명사"),
    ("emissions", "배출, 배기가스", "명사"),
    ("manner", "방식, 태도", "명사"),
    ("psychological", "정신적인, 심리적인", "형용사"),
    ("contest", "경쟁, 대회", "명사"),
    ("artificial", "인공적인", "형용사"),
    ("meanwhile", "그 동안에, 한편", "부사"),
    ("urban", "도시의", "형용사"),
    ("rarely", "드물게", "부사"),
    ("statistics", "통계, 통계학", "명사"),
    ("scene", "현장, 장면", "명사"),
    ("quit", "그만두다", "동사"),
    ("draft", "원고, 초안", "명사"),
    # 20차
    ("surgery", "수술", "명사"),
    ("appeal", "호소, 매력", "명사"),
    ("progress", "진전, 진전을 보이다", "명사"),
    ("crucial", "중대한, 결정적인", "형용사"),
    ("belong", "속하다", "동사"),
    ("wealth", "부유함, 풍부한 양", "명사"),
    ("ingredients", "재료들", "명사"),
    ("salary", "급여, 봉급", "명사"),
    ("practical", "실질적인", "형용사"),
    ("intellectual", "지적인", "형용사"),
    ("goods", "상품, 재산", "명사"),
    ("feedback", "피드백", "명사"),
    ("survey", "조사, 점검하다", "명사"),
    ("meditation", "명상", "명사"),
    ("symptoms", "증상들", "명사"),
    ("proof", "증명", "명사"),
    ("distinct", "뚜렷한, 확실한", "형용사"),
    ("apologize", "사과하다", "동사"),
    ("coverage", "범위", "명사"),
    ("surrounding", "인근의, 둘러싼", "형용사"),
    ("rent", "집세, 임대하다", "명사"),
    # 21차
    ("destroyed", "파괴된", "형용사"),
    ("restrictions", "제한들", "명사"),
    ("vital", "필수적인", "형용사"),
    ("eligible", "자격이 되는", "형용사"),
    ("loan", "대출", "명사"),
    ("immigrants", "이민자들", "명사"),
    ("executives", "경영진들", "명사"),
    ("resort", "의존하다, 휴양지", "동사"),
    ("cognitive", "인지의", "형용사"),
    ("prey", "먹이, 피해자", "명사"),
    ("universe", "우주", "명사"),
    ("evolution", "진화, 발전", "명사"),
    ("correlation", "상관관계", "명사"),
    ("capital", "수도, 자본금", "명사"),
    ("strike", "때리다, 파업", "동사"),
    ("proper", "제대로 된", "형용사"),
    ("extensive", "대규모의, 대대적인", "형용사"),
    ("assume", "추정하다", "동사"),
    ("convince", "납득시키다, 설득하다", "동사"),
    ("recover", "회복되다", "동사"),
    ("convenient", "편리한", "형용사"),
    ("era", "시대", "명사"),
    ("protest", "항의", "명사"),
    ("maximum", "최고의", "형용사"),
    ("confirmation", "확인", "명사"),
    ("inflation", "인플레이션", "명사"),
    # 22차
    ("solely", "오로지, 단독으로", "부사"),
    ("reluctant", "꺼리는, 주저하는", "형용사"),
    ("blame", "탓하다, 책임", "동사"),
    ("luggage", "짐", "명사"),
    ("conflict", "갈등", "명사"),
    ("habitat", "서식지", "명사"),
    ("renovations", "수리, 개조", "명사"),
    ("relevant", "관련된", "형용사"),
    ("gradually", "서서히", "부사"),
    ("disorders", "장애", "명사"),
    ("expenses", "비용", "명사"),
    ("phenomenon", "현상", "명사"),
    ("ethnic", "민족의", "형용사"),
    ("detect", "감지하다", "동사"),
    ("prepare", "준비하다", "동사"),
    ("compensation", "보상", "명사"),
    ("cancel", "취소하다", "동사"),
    ("relief", "안심", "명사"),
    ("award", "상, 수여하다", "명사"),
    ("renowned", "유명한, 명성 있는", "형용사"),
    ("satisfaction", "만족, 충족", "명사"),
    ("deposit", "보증금", "명사"),
    ("civilization", "문명", "명사"),
    ("administration", "관리", "명사"),
    # 23차
    ("pharmaceutical", "제약의", "형용사"),
    ("harvest", "수확하다", "동사"),
    ("distribution", "분배", "명사"),
    ("artifacts", "공예품들", "명사"),
    ("sector", "분야", "명사"),
    ("layer", "층", "명사"),
    ("layoffs", "해고", "명사"),
    ("republic", "공화국", "명사"),
    ("estimate", "추정", "명사"),
    ("subsequent", "차후의", "형용사"),
    ("conventional", "전통적인, 관습적인", "형용사"),
    ("tropical", "열대 지방의", "형용사"),
    ("absolutely", "틀림없이", "부사"),
    ("rapidly", "빨리, 신속히", "부사"),
    ("reflect", "반영하다", "동사"),
    ("vaccine", "백신", "명사"),
    ("urge", "촉구하다, 충동", "동사"),
    ("architecture", "건축 양식", "명사"),
    ("consequently", "그 결과, 따라서", "부사"),
    ("warranty", "품질 보증서", "명사"),
    ("anxiety", "염려, 불안", "명사"),
    ("infection", "감염", "명사"),
    ("outbreak", "발생", "명사"),
    # 24차
    ("pursue", "추구하다", "동사"),
    ("excessive", "과도한, 지나친", "형용사"),
    ("sensitive", "세심한, 감성 있는", "형용사"),
    ("authorities", "정부당국", "명사"),
    ("journey", "여정", "명사"),
    ("massive", "거대한", "형용사"),
    ("rural", "시골의, 지방의", "형용사"),
    ("craft", "공예, 기술", "명사"),
    ("empire", "제국, 거대 기업", "명사"),
    ("slightly", "약간", "부사"),
    ("principal", "주요한", "형용사"),
    ("fault", "잘못, 결함", "명사"),
    ("temporary", "일시적인", "형용사"),
    ("measure", "조치, 측정하다", "명사"),
    ("fossil", "화석", "명사"),
    ("merely", "그저, 단지", "부사"),
    ("sufficient", "충분한", "형용사"),
    ("federal", "연방제의", "형용사"),
    ("attract", "끌어들이다", "동사"),
    ("perception", "자각, 감지", "명사"),
    ("tuition", "수업료", "명사"),
    ("passion", "열정", "명사"),
    ("ethical", "윤리적인", "형용사"),
    ("constant", "끊임없는", "형용사"),
    ("insights", "통찰력", "명사"),
    # 25차
    ("reference", "언급, 참고", "명사"),
    ("institute", "기관", "명사"),
    ("institutions", "기관들", "명사"),
    ("immune", "면역성이 있는", "형용사"),
    ("subscription", "구독", "명사"),
    ("internal", "내부의", "형용사"),
    ("external", "외부의", "형용사"),
    ("virtually", "사실상, 거의", "부사"),
    ("inspection", "점검", "명사"),
    ("permanent", "영구적인", "형용사"),
    ("peak", "절정", "명사"),
    ("soil", "국토", "명사"),
    ("treaty", "조약", "명사"),
    ("infrastructure", "공공 기반 시설", "명사"),
    ("interpretation", "해석, 설명", "명사"),
    ("medieval", "중세의", "형용사"),
    ("qualified", "자격을 갖춘", "형용사"),
    ("overcome", "극복하다", "동사"),
    ("portion", "일부분", "명사"),
    ("hazardous", "위험한", "형용사"),
    ("globe", "세계", "명사"),
    ("curb", "억제하다", "동사"),
    ("predators", "포식자들", "명사"),
    ("approximately", "거의, 가까이", "부사"),
    ("caution", "경고", "명사"),
    ("exclusive", "독점적인", "형용사"),
    # 26차
    ("praise", "칭찬하다, 칭찬", "동사"),
    ("principles", "원칙들", "명사"),
    ("harsh", "가혹한", "형용사"),
    ("stable", "안정적인", "형용사"),
    ("attitude", "태도", "명사"),
    ("exception", "예외", "명사"),
    ("exceptional", "이례적인, 특출난", "형용사"),
    ("universal", "일반적인, 보편적인", "형용사"),
    ("revenue", "수익, 수입", "명사"),
    ("endangered", "멸종 위기에 처한", "형용사"),
    ("liberal", "진보적인, 자유로운", "형용사"),
    ("resistance", "저항", "명사"),
    ("perspective", "관점", "명사"),
    ("expedition", "탐험", "명사"),
    ("hypothesis", "가설", "명사"),
    ("disposal", "처분", "명사"),
    ("prescription", "처방전", "명사"),
    ("valid", "유효한, 타당한", "형용사"),
    ("justice", "공정성", "명사"),
    ("supreme", "최고의", "형용사"),
    ("reproduction", "번식, 복제", "명사"),
    # 27차
    ("consistent", "일관된, 한결같은", "형용사"),
    ("ancestors", "선조들", "명사"),
    ("welfare", "복지", "명사"),
    ("exotic", "이국적인", "형용사"),
    ("nutrients", "영양소", "명사"),
    ("launch", "시작하다, 출시하다", "동사"),
    ("legitimate", "타당한, 합법적인", "형용사"),
    ("peers", "동료들", "명사"),
    ("strength", "힘, 강인함", "명사"),
    ("cuisine", "요리법", "명사"),
    ("collaboration", "공동 작업, 협력", "명사"),
    ("chronic", "만성적인", "형용사"),
    ("aspect", "측면", "명사"),
    ("impulse", "충동, 자극", "명사"),
    ("democracy", "민주주의", "명사"),
    ("possess", "소유하다", "동사"),
    ("compromise", "타협", "명사"),
    # 28차
    ("intense", "열정적인, 강렬한", "형용사"),
    ("dairy", "유제품의", "형용사"),
    ("biological", "생물학의", "형용사"),
    ("impressive", "인상적인", "형용사"),
    ("narrative", "서술", "명사"),
    ("hybrid", "잡종, 혼합물", "명사"),
    ("lucrative", "수익성이 좋은", "형용사"),
    ("dietary", "식이요법의", "형용사"),
    ("wages", "임금", "명사"),
    ("emerging", "최근에 생겨난", "형용사"),
    ("routine", "일상, 틀", "명사"),
    ("commission", "위원회, 수당", "명사"),
    ("prominent", "중요한, 눈에 잘 띄는", "형용사"),
    ("alert", "기민한", "형용사"),
    ("context", "맥락", "명사"),
    ("dominant", "우세한", "형용사"),
    ("sacrifice", "희생", "명사"),
    ("circumstances", "상황들", "명사"),
    ("renew", "갱신하다", "동사"),
    ("typical", "전형적인", "형용사"),
    ("contrary", "정반대되는", "형용사"),
    ("vulnerable", "연약한, 취약한", "형용사"),
    ("tribes", "부족들", "명사"),
    ("booking", "예약", "명사"),
    ("merchandise", "상품", "명사"),
    # 29차
    ("duties", "의무, 임무", "명사"),
    ("preserve", "보존하다, 지키다", "동사"),
    ("detrimental", "해로운", "형용사"),
    ("renaissance", "부흥, 르네상스 시대", "명사"),
    ("destruction", "파멸, 말살", "명사"),
    ("dispute", "분쟁", "명사"),
    ("indicate", "나타내다", "동사"),
    ("encounter", "맞닥뜨리다", "동사"),
    ("legislation", "법률 제정", "명사"),
    ("abstract", "추상적인", "형용사"),
    ("penalty", "처벌, 불이익", "명사"),
    ("resolve", "해결하다", "동사"),
    ("investigation", "조사, 수사", "명사"),
    ("intake", "섭취, 신규 인원", "명사"),
    ("extent", "규모, 정도", "명사"),
    ("mainstream", "주류", "명사"),
    ("landscape", "풍경", "명사"),
    ("addiction", "중독", "명사"),
    ("specialty", "전문, 특산물", "명사"),
    ("engage", "관여하다, 사로잡다", "동사"),
    ("faculty", "능력", "명사"),
    # 30차
    ("shame", "수치심", "명사"),
    ("linguistic", "언어적인", "형용사"),
    ("census", "인구 조사", "명사"),
    ("burden", "부담", "명사"),
    ("charity", "자선, 관용", "명사"),
    ("downturn", "부진, 침체", "명사"),
    ("branch", "나뭇가지, 지점", "명사"),
    ("extinct", "멸종된", "형용사"),
    ("foundation", "토대", "명사"),
    ("deserve", "~할 자격이 있다", "동사"),
    ("unprecedented", "전례 없는", "형용사"),
    ("notion", "개념", "명사"),
    ("automobile", "자동차", "명사"),
    ("reasonable", "합리적인, 타당한", "형용사"),
    ("substitute", "대체품", "명사"),
    ("tragedy", "비극", "명사"),
    ("modest", "겸손한, 보통의", "형용사"),
    ("adhere", "들러붙다, 고수하다", "동사"),
    ("traits", "특성들", "명사"),
    ("profound", "엄청난, 깊은", "형용사"),
    ("leisure", "여가", "명사"),
    ("censorship", "검열", "명사"),
    ("theft", "절도", "명사"),
    ("adequate", "충분한, 적절한", "형용사"),
    ("acquaintances", "지인들", "명사"),
    ("conscious", "의식하는", "형용사"),
    ("cooperation", "협력", "명사"),
    # 31차
    ("portable", "휴대용의", "형용사"),
    ("absence", "결석, 결핍", "명사"),
    ("monetary", "통화(화폐)의", "형용사"),
    ("insomnia", "불면증", "명사"),
    ("satellite", "위성", "명사"),
    ("advocates", "지지자들", "명사"),
    ("justify", "정당화시키다", "동사"),
    ("sculpture", "조각품", "명사"),
    ("restore", "회복시키다", "동사"),
    ("contaminated", "오염된", "형용사"),
    ("ordinary", "일상적인, 평범한", "형용사"),
    ("foster", "조성하다, 증진시키다", "동사"),
    ("complimentary", "무료의, 칭찬하는", "형용사"),
    ("linear", "직선적인", "형용사"),
    ("substantial", "상당한", "형용사"),
    ("indigenous", "토착의", "형용사"),
    ("intelligence", "지능, 지성", "명사"),
    ("bond", "유대", "명사"),
    ("vary", "서로 다르다", "동사"),
    ("derived", "유래된", "형용사"),
    ("heritage", "유산", "명사"),
    ("polar", "극지의, 양극의", "형용사"),
    # 32차
    ("reception", "접수처, 환영 연회", "명사"),
    ("efficacy", "효험", "명사"),
    ("ritual", "의식, 의례", "명사"),
    ("reductions", "삭감, 할인", "명사"),
    ("obese", "비만인", "형용사"),
    ("mutual", "상호간의", "형용사"),
    ("ongoing", "계속 진행 중인", "형용사"),
    ("viable", "실행 가능한", "형용사"),
    ("arena", "경기장, 무대", "명사"),
    ("primitive", "원시 사회의, 초기의", "형용사"),
    ("predominantly", "대부분, 주로", "부사"),
    ("neural", "신경의", "형용사"),
    ("medication", "약, 약물 치료", "명사"),
    ("maintenance", "유지", "명사"),
    ("prime", "주요한, 최고의", "형용사"),
    ("sake", "동기, 목적", "명사"),
    ("passionate", "열정적인", "형용사"),
    ("rite", "의례", "명사"),
    ("anthropology", "인류학", "명사"),
    ("autism", "자폐증", "명사"),
    ("plagiarism", "표절", "명사"),
    ("combat", "전투, 방지하다", "명사"),
    ("petition", "탄원서", "명사"),
    ("rear", "뒤쪽", "명사"),
    # 33차
    ("reversed", "거꾸로 된, 뒤집힌", "형용사"),
    ("outstanding", "뛰어난, 두드러진", "형용사"),
    ("criteria", "기준, 표준", "명사"),
    ("liberty", "자유", "명사"),
    ("discipline", "훈육", "명사"),
    ("fraud", "사기꾼, 가짜", "명사"),
    ("boulevard", "도로", "명사"),
    ("worn", "닳은, 몹시 지쳐 보이는", "형용사"),
    ("spare", "남는, 할애하다", "형용사"),
    ("sparingly", "절약하여", "부사"),
    ("remote", "외진, 먼", "형용사"),
    ("enhance", "높이다, 향상시키다", "동사"),
    ("facilitate", "가능하게 하다", "동사"),
    ("shift", "옮기다", "동사"),
    ("psychiatric", "정신 의학의", "형용사"),
    ("aboriginal", "원주민의", "형용사"),
    ("hikes", "급등", "명사"),
    ("scheme", "책략", "명사"),
    ("hazard", "위험 요소", "명사"),
    ("desertification", "사막화", "명사"),
    ("lease", "임대차 계약", "명사"),
    ("syllabus", "커리큘럼", "명사"),
    ("transit", "수송, 환승", "명사"),
    ("genuine", "진짜의, 진실한", "형용사"),
    ("considerable", "상당한, 많은", "형용사"),
    ("elementary", "초보의, 근본적인", "형용사"),
    ("antibiotics", "항생물질", "명사"),
    ("demonstrate", "입증하다, 보여주다", "동사"),
    ("transactions", "거래, 매매", "명사"),
    # 34차
    ("entrepreneurs", "기업가들", "명사"),
    ("reign", "통치 기간", "명사"),
    ("merit", "가치, 장점", "명사"),
    ("wilderness", "황무지", "명사"),
    ("adhesive", "들러붙는, 접착제", "형용사"),
    ("dean", "학과장", "명사"),
    ("acids", "산", "명사"),
    ("cardiovascular", "심혈관의", "형용사"),
    ("resurrection", "부활", "명사"),
    ("comet", "혜성", "명사"),
    ("surpass", "능가하다, 뛰어넘다", "동사"),
    ("assert", "주장하다, 확고히 하다", "동사"),
    ("procure", "구하다, 확보하다", "동사"),
    ("lawn", "잔디", "명사"),
    ("consensus", "합의", "명사"),
    ("comply", "따르다, 준수하다", "동사"),
    ("compulsory", "강제적인, 의무적인", "형용사"),
    ("liability", "부채", "명사"),
    ("demolition", "파괴, 폭파", "명사"),
    ("withstand", "견뎌 내다", "동사"),
    ("exclusion", "제외, 배제", "명사"),
    ("magnitude", "중요도, 지진 규모", "명사"),
    ("instant", "즉각적인", "형용사"),
    ("initiative", "계획, 주도권", "명사"),
    ("presidential", "대통령의", "형용사"),
    # 35차
    ("novice", "초보자", "명사"),
    ("debris", "잔해", "명사"),
    ("deficit", "적자", "명사"),
    ("acclaim", "칭송하다, 칭찬", "동사"),
    ("gear", "기어", "명사"),
    ("advisory", "자문의", "형용사"),
    ("venue", "장소", "명사"),
    ("abuse", "남용, 학대", "명사"),
    ("feasible", "실현 가능한", "형용사"),
    ("divine", "신성한", "형용사"),
    ("norms", "규준, 규범", "명사"),
    ("predicament", "곤경, 궁지", "명사"),
    ("reptiles", "파충류", "명사"),
    ("affiliation", "소속, 가입", "명사"),
    ("morale", "의욕, 사기", "명사"),
    ("pedestrian", "보행자", "명사"),
    ("retention", "보유, 잔류", "명사"),
    ("disciplinary", "징계의", "형용사"),
    ("cope", "대처하다", "동사"),
    ("solicit", "간청하다", "동사"),
    ("municipal", "지방 자치제의", "형용사"),
    ("discrepancy", "차이", "명사"),
    ("attorney", "변호사, 대리인", "명사"),
    # 36차
    ("rogue", "사기꾼, 악당", "명사"),
    ("grid", "격자판", "명사"),
    ("assign", "맡기다, 선임하다", "동사"),
    ("tenants", "세입자들", "명사"),
    ("detergent", "세제", "명사"),
    ("resurgence", "재기", "명사"),
    ("strive", "분투하다", "동사"),
    ("paramount", "가장 중요한, 최고의", "형용사"),
    ("colossal", "거대한, 엄청난", "형용사"),
    ("tremendous", "엄청난, 굉장한", "형용사"),
    ("enormous", "거대한, 막대한", "형용사"),
    ("authentic", "진짜 같은", "형용사"),
    ("dementia", "치매", "명사"),
    ("deter", "단념시키다", "동사"),
    ("susceptible", "예민한, 민감한", "형용사"),
    ("undergo", "겪다", "동사"),
    ("corporations", "기업들", "명사"),
    ("onset", "시작", "명사"),
    ("imposing", "눈길을 끄는, 인상적인", "형용사"),
    ("turnover", "매출량, 이직률", "명사"),
    ("occupancy", "사용", "명사"),
    ("applicable", "해당되는", "형용사"),
    ("plague", "전염병", "명사"),
    ("intricate", "복잡한", "형용사"),
    ("clan", "씨족, 집단", "명사"),
    ("comprise", "구성하다", "동사"),
    # 37차
    ("conserve", "아끼다, 보존하다", "동사"),
    ("sheer", "순전한", "형용사"),
    ("hatch", "부화하다, 기획하다", "동사"),
    ("severity", "격렬, 엄격", "명사"),
    ("extravagant", "사치스러운, 화려한", "형용사"),
    ("speculate", "추측하다, 투기하다", "동사"),
    ("speculation", "추측, 투기", "명사"),
    ("rigorous", "엄격한", "형용사"),
    ("alter", "바꾸다", "동사"),
    ("inclusion", "포함", "명사"),
    ("gross", "중대한", "형용사"),
    ("hinder", "방해하다", "동사"),
    ("mediocre", "보통의, 평범한", "형용사"),
    ("tenure", "재임, 종신 재직권", "명사"),
    ("overdue", "기한이 지난", "형용사"),
    ("wary", "조심하는", "형용사"),
    ("prestigious", "명망 있는", "형용사"),
    ("prevalent", "일반적인, 널리 퍼져 있는", "형용사"),
    ("lethal", "치명적인", "형용사"),
    ("vessel", "선박, 혈관", "명사"),
    ("alternate", "번갈아 생기는", "형용사"),
    ("alliance", "연합, 동맹", "명사"),
    ("intent", "목적", "명사"),
    ("turmoil", "소란, 혼란", "명사"),
    ("proponents", "지지자들", "명사"),
    ("synthetic", "합성한, 종합적인", "형용사"),
    # 38차
    ("commodity", "상품, 물품", "명사"),
    ("accommodation", "숙소, 시설", "명사"),
    ("magnificent", "장엄한", "형용사"),
    ("eradication", "근절, 박멸", "명사"),
    ("avid", "열렬한, 열망하는", "형용사"),
    ("keen", "예민한, 열렬한", "형용사"),
    ("accumulate", "축적하다", "동사"),
    ("precipitation", "강수량", "명사"),
    ("strain", "부담", "명사"),
    ("prone", "하기 쉬운", "형용사"),
    ("specimen", "표본", "명사"),
    ("yield", "생산하다, 항복하다", "동사"),
    ("dismiss", "묵살하다, 해고하다", "동사"),
    ("unison", "화합", "명사"),
    ("surge", "밀려들다, 휩싸다", "동사"),
    ("replicate", "복제하다", "동사"),
    ("erosion", "부식", "명사"),
    ("prosperous", "번창한", "형용사"),
    ("prosper", "번영하다", "동사"),
    ("demise", "종말, 죽음", "명사"),
    ("vertebrates", "척추동물", "명사"),
    ("console", "위로하다", "동사"),
    ("invasion", "침략, 침해", "명사"),
    ("conform", "따르다", "동사"),
    # 39차
    ("refined", "세련된", "형용사"),
    ("repercussions", "영향들", "명사"),
    ("reminiscent", "연상시키는", "형용사"),
    ("boon", "요긴한 것", "명사"),
    ("realm", "왕국, 영역", "명사"),
    ("heed", "주의를 기울이다", "동사"),
    ("maternity", "어머니인 상태", "명사"),
    ("culinary", "요리의", "형용사"),
    ("tariffs", "관세", "명사"),
    ("stranded", "발이 묶인", "형용사"),
    ("surveillance", "감시", "명사"),
    ("hectic", "정신없이 바쁜, 빡빡한", "형용사"),
    ("inmates", "수감자들", "명사"),
    ("rehabilitation", "갱생", "명사"),
    ("pension", "연금", "명사"),
    ("confidential", "비밀의", "형용사"),
    ("lag", "뒤에 처지다", "동사"),
    ("outreach", "봉사활동", "명사"),
    ("devoid", "~이 전혀 없는", "형용사"),
    ("consent", "동의", "명사"),
    # 40차
    ("garments", "의복", "명사"),
    ("siege", "포위", "명사"),
    ("therapeutic", "치료상의", "형용사"),
    ("incur", "발생시키다", "동사"),
    ("ventilation", "환기, 통풍", "명사"),
    ("heroic", "영웅적인", "형용사"),
    ("substantive", "실질적인", "형용사"),
    ("implications", "결과, 영향", "명사"),
    ("commence", "시작되다", "동사"),
    ("intact", "온전한", "형용사"),
    ("undertaking", "약속, 일", "명사"),
    ("phenomenal", "경이적인", "형용사"),
    ("forge", "위조하다", "동사"),
    ("furnishing", "비품, 가구", "명사"),
    ("doomed", "불운한", "형용사"),
    ("payroll", "임금", "명사"),
    ("sediment", "퇴적물", "명사"),
    ("heir", "상속인", "명사"),
    ("contradict", "반박하다, 모순되다", "동사"),
    ("downfall", "몰락의 원인", "명사"),

    # 41차
    ("behalf", "이익, 대리", "명사"),
    ("inferior", "열등한", "형용사"),
    ("reimburse", "환급하다", "동사"),
    ("equivalent", "동등한", "형용사"),
    ("induce", "유도하다", "동사"),
    ("virulent", "맹렬한, 독성의", "형용사"),
    ("asylum", "망명, 보호시설", "명사"),
    ("inception", "시작, 발단", "명사"),
    ("outlaw", "불법화하다", "동사"),
    ("convoy", "호송대", "명사"),
    ("decree", "법령, 칙령", "명사"),
    ("ballot", "투표", "명사"),
    ("crater", "분화구", "명사"),
    ("expatriate", "해외 거주자", "명사"),
    ("sewage", "하수, 오수", "명사"),
    ("detachment", "분리, 초연함", "명사"),
    ("concussions", "뇌진탕", "명사"),
    ("chivalry", "기사도", "명사"),
    ("barred", "금지된", "형용사"),
    ("fleet", "함대", "명사"),
    ("aristocracy", "귀족 정치", "명사"),
    ("conscientious", "양심적인", "형용사"),

    # 42차
    ("infertile", "불임의, 불모의", "형용사"),
    ("stabilize", "안정시키다", "동사"),
    ("futile", "헛된", "형용사"),
    ("astronomical", "천문학적인", "형용사"),
    ("awe", "경외심을 갖게 하다", "동사"),
    ("sovereign", "군주", "명사"),
    ("fragile", "깨지기 쉬운", "형용사"),
    ("dismissive", "무시하는", "형용사"),
    ("ponder", "곰곰이 생각하다", "동사"),
    ("undue", "과도한", "형용사"),
    ("endorse", "지지하다", "동사"),
    ("refute", "반박하다", "동사"),
    ("patronage", "후원", "명사"),
    ("flesh", "살, 육체", "명사"),
    ("trail", "흔적, 오솔길", "명사"),
    ("longstanding", "오랜, 오래된", "형용사"),
    ("calculus", "미적분학", "명사"),
    ("brutal", "잔인한", "형용사"),
    ("superintendent", "감독관", "명사"),
    ("impending", "임박한", "형용사"),
    ("hype", "과대광고", "명사"),
    ("envision", "상상하다", "동사"),
    ("patriotism", "애국심", "명사"),

    # 43차
    ("inflated", "부풀려진", "형용사"),
    ("referendum", "국민투표", "명사"),
    ("breach", "위반, 균열", "명사"),
    ("eventual", "최종적인", "형용사"),
    ("assembly", "집회, 조립", "명사"),
    ("evacuate", "대피시키다", "동사"),
    ("punctual", "시간을 엄수하는", "형용사"),
    ("rhetoric", "수사학, 미사여구", "명사"),
    ("subversive", "전복적인", "형용사"),
    ("vandalism", "공공기물 파손", "명사"),
    ("swear", "맹세하다", "동사"),
    ("exorbitant", "터무니없이 비싼", "형용사"),
    ("plunge", "급락하다", "동사"),
    ("stringent", "엄격한", "형용사"),
    ("dire", "극심한", "형용사"),
    ("scrutiny", "면밀한 조사", "명사"),
    ("precursor", "선구자, 전조", "명사"),
    ("influx", "유입", "명사"),
    ("hue", "색조", "명사"),
    ("spite", "악의", "명사"),
    ("impurities", "불순물", "명사"),
    ("provincial", "지방의", "형용사"),
    ("skewed", "왜곡된", "형용사"),

    # 44차
    ("detour", "우회로", "명사"),
    ("anarchy", "무정부 상태", "명사"),
    ("rally", "집결하다", "동사"),
    ("cavalry", "기병대", "명사"),
    ("initiate", "시작하다", "동사"),
    ("arid", "건조한", "형용사"),
    ("perishable", "부패하기 쉬운", "형용사"),
    ("irrigation", "관개", "명사"),
    ("circuit", "회로, 순환", "명사"),
    ("alleged", "혐의가 있는", "형용사"),
    ("unravel", "풀다, 밝히다", "동사"),
    ("upscale", "고급의", "형용사"),
    ("proliferate", "급증하다", "동사"),
    ("revamp", "개조하다", "동사"),
    ("archaic", "고풍의, 구식의", "형용사"),
    ("thesis", "논문, 논지", "명사"),
    ("resilient", "회복력 있는", "형용사"),
    ("condescending", "거드름 피우는", "형용사"),
    ("vicinity", "근처, 인근", "명사"),
    ("heinous", "극악무도한", "형용사"),
    ("vigilance", "경계", "명사"),
    ("glimpse", "잠깐 봄", "명사"),
    ("antidepressants", "항우울제", "명사"),
    ("versatile", "다재다능한", "형용사"),

    # 45차
    ("trepidation", "두려움, 전율", "명사"),
    ("customary", "관습적인", "형용사"),
    ("philanthropic", "박애주의적인", "형용사"),
    ("rectify", "수정하다", "동사"),
    ("overrated", "과대평가된", "형용사"),
    ("fad", "일시적 유행", "명사"),
    ("conducive", "도움이 되는", "형용사"),
    ("aspirations", "열망", "명사"),
    ("intimidating", "위협적인", "형용사"),
    ("ingrained", "뿌리 깊은", "형용사"),
    ("imminent", "임박한", "형용사"),
    ("rudimentary", "기초적인", "형용사"),
    ("empirical", "경험적인", "형용사"),
    ("jeopardize", "위태롭게 하다", "동사"),
    ("enticing", "매혹적인", "형용사"),
    ("peasants", "농민", "명사"),
    ("conversion", "전환, 개종", "명사"),
    ("marginalized", "소외된", "형용사"),
    ("extant", "현존하는", "형용사"),
    ("offset", "상쇄하다", "동사"),
    ("lure", "유혹하다", "동사"),
    ("pedagogy", "교육학", "명사"),
    ("primates", "영장류", "명사"),
    ("daunting", "버거운, 위압적인", "형용사"),

    # 46차
    ("paralyzed", "마비된", "형용사"),
    ("secular", "세속적인", "형용사"),
    ("fringe", "변두리, 가장자리", "명사"),
    ("denote", "나타내다", "동사"),
    ("horrific", "끔찍한", "형용사"),
    ("juveniles", "청소년", "명사"),
    ("plethora", "과잉, 넘침", "명사"),
    ("correspondence", "서신, 일치", "명사"),
    ("dissertation", "논문", "명사"),
    ("provocative", "도발적인", "형용사"),
    ("altruism", "이타주의", "명사"),
    ("sturdy", "튼튼한", "형용사"),
    ("crude", "미정제의, 조잡한", "형용사"),
    ("benign", "양성의, 온화한", "형용사"),
    ("stark", "황량한, 완전한", "형용사"),
    ("assassination", "암살", "명사"),
    ("deceitful", "기만적인", "형용사"),
    ("deceptive", "속이는", "형용사"),
    ("woes", "고통, 불행", "명사"),
    ("appellation", "명칭", "명사"),
    ("delinquent", "비행의", "형용사"),
    ("maneuver", "작전, 책략", "명사"),
    ("frivolous", "경솔한", "형용사"),
    ("exile", "추방", "명사"),

    # 47차
    ("vigorous", "활기찬", "형용사"),
    ("dignitaries", "고위인사", "명사"),
    ("fiscal", "재정의", "형용사"),
    ("allied", "동맹의", "형용사"),
    ("vice", "악덕, 부도덕", "명사"),
    ("vicious", "잔인한, 악의적인", "형용사"),
    ("uproar", "소란, 논란", "명사"),
    ("potent", "강력한", "형용사"),
    ("discretion", "재량, 신중함", "명사"),
    ("astonishing", "놀라운", "형용사"),
    ("astounding", "경이로운", "형용사"),
    ("terrain", "지형", "명사"),
    ("hilarious", "매우 우스운", "형용사"),
    ("famine", "기근", "명사"),
    ("procrastination", "미루기", "명사"),
    ("mergers", "합병", "명사"),
    ("rebellion", "반란", "명사"),
    ("counterfeiting", "위조", "명사"),
    ("domain", "영역, 분야", "명사"),
    ("hierarchy", "계층 구조", "명사"),
    ("patriarchy", "가부장제", "명사"),
    ("scarcity", "부족, 희소성", "명사"),
    ("debilitating", "쇠약하게 하는", "형용사"),
    ("aesthetic", "미적인", "형용사"),

    # 48차
    ("empathy", "공감", "명사"),
    ("wholly", "완전히", "부사"),
    ("turbulence", "난기류, 혼란", "명사"),
    ("affirmative", "긍정적인", "형용사"),
    ("avian", "조류의", "형용사"),
    ("impoverished", "빈곤한", "형용사"),
    ("paranormal", "초자연적인", "형용사"),
    ("pathological", "병적인", "형용사"),
    ("vapor", "증기", "명사"),
    ("trajectory", "궤도, 경로", "명사"),
    ("erroneous", "잘못된", "형용사"),
    ("fertility", "비옥함, 생식력", "명사"),
    ("acculturation", "문화 동화", "명사"),
    ("distraught", "매우 혼란스러운", "형용사"),
    ("strained", "긴장된", "형용사"),
    ("naval", "해군의", "형용사"),
    ("expenditure", "지출", "명사"),
    ("pundits", "전문가", "명사"),
    ("anthem", "국가, 찬가", "명사"),
    ("transparent", "투명한", "형용사"),
    ("immorality", "부도덕", "명사"),
    ("communism", "공산주의", "명사"),
    ("senator", "상원의원", "명사"),

    # 49차
    ("contrived", "인위적인", "형용사"),
    ("repressive", "억압적인", "형용사"),
    ("oppressive", "압제적인", "형용사"),
    ("carnivore", "육식동물", "명사"),
    ("inauguration", "취임식", "명사"),
    ("overarching", "전반적인", "형용사"),
    ("obscurity", "무명, 불분명함", "명사"),
    ("exquisite", "정교한, 절묘한", "형용사"),
    ("tame", "길든, 순한", "형용사"),
    ("regime", "정권, 체제", "명사"),
    ("regimen", "규칙적인 생활방식", "명사"),
    ("alteration", "변경", "명사"),
    ("dubious", "의심스러운", "형용사"),
    ("biannual", "연 2회의", "형용사"),
    ("finite", "유한한", "형용사"),
    ("custody", "구금, 보호", "명사"),
    ("pivotal", "중추적인", "형용사"),
    ("transmit", "전송하다", "동사"),
    ("viral", "바이러스성의", "형용사"),
    ("mundane", "평범한", "형용사"),
    ("surplus", "잉여", "명사"),
    ("interim", "임시의", "형용사"),

    # 50차
    ("deferred", "연기된", "형용사"),
    ("render", "만들다, 제공하다", "동사"),
    ("basin", "분지, 대야", "명사"),
    ("logistical", "물류의", "형용사"),
    ("tentative", "잠정적인", "형용사"),
    ("volatile", "변덕스러운, 휘발성의", "형용사"),
    ("excavations", "발굴", "명사"),
    ("embroiled", "분쟁에 휘말린", "형용사"),
    ("regression", "퇴행", "명사"),
    ("abysmal", "형편없는", "형용사"),
    ("ancestry", "조상", "명사"),
    ("recollect", "회상하다", "동사"),
    ("conviction", "유죄 판결, 신념", "명사"),
    ("reflection", "반성, 반영", "명사"),
    ("whimsical", "변덕스러운", "형용사"),
    ("plummet", "급락하다", "동사"),
    ("unequivocal", "명백한", "형용사"),
    ("grim", "암울한", "형용사"),
    ("prototypical", "전형적인", "형용사"),
    ("engrossed", "몰두한", "형용사"),

    # 51차
    ("splendid", "훌륭한", "형용사"),
    ("unwind", "긴장을 풀다", "동사"),
    ("tedious", "지루한", "형용사"),
    ("esoteric", "난해한", "형용사"),
    ("renounce", "포기하다", "동사"),
    ("abstain", "삼가다", "동사"),
    ("apprehensive", "걱정하는", "형용사"),
    ("insincere", "불성실한", "형용사"),
    ("rampant", "만연한", "형용사"),
    ("repudiate", "부인하다", "동사"),
    ("lenient", "관대한", "형용사"),
    ("emancipated", "해방된", "형용사"),
    ("havoc", "혼란, 대혼란", "명사"),
    ("parasite", "기생충", "명사"),
    ("ulterior", "숨겨진", "형용사"),
    ("retribution", "응보, 보복", "명사"),
    ("surreptitiously", "몰래", "부사"),
    ("withdraw", "철수하다", "동사"),
    ("nominees", "후보자", "명사"),
    ("testimonials", "추천서", "명사"),
    ("stunned", "충격받은", "형용사"),
    ("coup", "쿠데타", "명사"),
    ("impede", "방해하다", "동사"),
    ("masculine", "남성적인", "형용사"),

    # 52차
    ("confer", "수여하다, 협의하다", "동사"),
    ("prophecy", "예언", "명사"),
    ("replenish", "보충하다", "동사"),
    ("intrigue", "흥미를 끌다", "동사"),
    ("tepid", "미지근한", "형용사"),
    ("bereavement", "사별", "명사"),
    ("frigid", "매우 추운", "형용사"),
    ("scant", "불충분한", "형용사"),
    ("preliminary", "예비의", "형용사"),
    ("anatomical", "해부학적인", "형용사"),
    ("sanctuary", "성역, 피난처", "명사"),
    ("infancy", "유아기", "명사"),
    ("discharge", "방출하다", "동사"),
    ("decency", "품위", "명사"),
    ("scattered", "흩어진", "형용사"),
    ("outcry", "강한 항의", "명사"),
    ("convict", "유죄 판결을 내리다", "동사"),
    ("prudent", "신중한", "형용사"),
    ("subtlety", "미묘함", "명사"),
    ("sweeping", "광범위한", "형용사"),
    ("anomalous", "변칙적인", "형용사"),
    ("transient", "일시적인", "형용사"),
    ("callous", "냉담한", "형용사"),

    # 53차
    ("suffice", "충분하다", "동사"),
    ("extraterrestrial", "외계의", "명사"),
    ("snobbish", "속물적인", "형용사"),
    ("inhibit", "억제하다", "동사"),
    ("superb", "훌륭한", "형용사"),
    ("archive", "기록 보관소", "명사"),
    ("layover", "경유, 단기 체류", "명사"),
    ("validate", "검증하다", "동사"),
    ("wretched", "비참한", "형용사"),
    ("barbaric", "야만적인", "형용사"),
    ("inhumane", "비인도적인", "형용사"),
    ("dissent", "이의, 반대", "명사"),
    ("candor", "솔직함", "명사"),
    ("rife", "만연한", "형용사"),
    ("savvy", "요령, 지식", "명사"),
    ("prenatal", "출산 전의", "형용사"),
    ("seizures", "발작", "명사"),
    ("daring", "대담한", "형용사"),
    ("disincentive", "억제 요인", "명사"),

    # 54차
    ("resuscitate", "소생시키다", "동사"),
    ("retaliation", "보복", "명사"),
    ("imperative", "필수적인", "형용사"),
    ("veracity", "진실성", "명사"),
    ("fertile", "비옥한", "형용사"),
    ("bleak", "황량한, 암울한", "형용사"),
    ("abusive", "학대하는", "형용사"),
    ("dismal", "음울한", "형용사"),
    ("reconciliation", "화해", "명사"),
    ("thermal", "열의", "형용사"),
    ("affluent", "부유한", "형용사"),
    ("eternal", "영원한", "형용사"),
    ("override", "우선시하다", "동사"),
    ("wield", "행사하다", "동사"),
    ("omission", "누락", "명사"),
    ("conjure", "떠올리다", "동사"),
    ("yearning", "갈망", "명사"),
    ("enforce", "시행하다", "동사"),
    ("reckless", "무모한", "형용사"),
    ("plausible", "그럴듯한", "형용사"),
    ("culpable", "책임이 있는", "형용사"),
    ("ramifications", "결과, 파급 효과", "명사"),

    # 55차
    ("probation", "보호 관찰", "명사"),
    ("probes", "탐사선, 조사", "명사"),
    ("anguish", "고통", "명사"),
    ("indicative", "나타내는", "형용사"),
    ("tenet", "원칙, 신조", "명사"),
    ("subterranean", "지하의", "형용사"),
    ("obsolete", "구식의", "형용사"),
    ("oblivious", "의식하지 못하는", "형용사"),
    ("devout", "독실한", "형용사"),
    ("delicacy", "섬세함, 진미", "명사"),
    ("evasion", "회피", "명사"),
    ("ostensibly", "표면상으로", "부사"),
    ("omens", "징조", "명사"),
    ("disobedience", "불복종", "명사"),
    ("reinstate", "복직시키다", "동사"),
    ("grandiose", "웅장한", "형용사"),
    ("predatory", "약탈적인", "형용사"),
    ("acuity", "예리함", "명사"),
    ("authoritative", "권위 있는", "형용사"),
    ("villain", "악당", "명사"),
    ("incarceration", "투옥", "명사"),

    # 56차
    ("insulate", "절연하다", "동사"),
    ("insulator", "절연체", "명사"),
    ("preclude", "배제하다", "동사"),
    ("inverse", "역의", "형용사"),
    ("tribute", "공물, 경의", "명사"),
    ("sterilization", "살균, 불임 수술", "명사"),
    ("foundational", "기초적인", "형용사"),
    ("fervor", "열정", "명사"),
    ("spherical", "구형의", "형용사"),
    ("avert", "피하다", "동사"),
    ("resonance", "공명, 울림", "명사"),
    ("exacerbated", "악화된", "형용사"),
    ("allay", "완화하다", "동사"),
    ("entails", "수반하다", "동사"),
    ("encompass", "포함하다", "동사"),
    ("arrogance", "오만", "명사"),
    ("bereft", "빼앗긴", "형용사"),
    ("repeal", "폐지하다", "동사"),
    ("congested", "혼잡한", "형용사"),
    ("sumptuous", "호화로운", "형용사"),
    ("collide", "충돌하다", "동사"),
    ("prerequisite", "전제 조건", "명사"),

    # 57차
    ("aristocratic", "귀족적인", "형용사"),
    ("ordinances", "조례", "명사"),
    ("ardent", "열렬한", "형용사"),
    ("burial", "장례", "명사"),
    ("cerebral", "지적인, 대뇌의", "형용사"),
    ("meddle", "참견하다", "동사"),
    ("imprecise", "부정확한", "형용사"),
    ("alleviate", "완화하다", "동사"),
    ("caustic", "신랄한", "형용사"),
    ("precarious", "불안정한", "형용사"),
    ("seduction", "유혹", "명사"),
    ("equilibrium", "균형", "명사"),
    ("incompatible", "양립할 수 없는", "형용사"),
    ("sequel", "속편", "명사"),
    ("raid", "급습", "명사"),
    ("compartment", "칸, 구획", "명사"),
    ("manifestation", "표현, 징후", "명사"),
    ("perturbed", "당황한", "형용사"),
    ("circumvent", "우회하다", "동사"),
    ("outraged", "격분한", "형용사"),
    ("intermission", "휴식 시간", "명사"),

    # 58차
    ("crusade", "십자군, 운동", "명사"),
    ("relish", "즐기다", "동사"),
    ("ameliorate", "개선하다", "동사"),
    ("inequitable", "불공평한", "형용사"),
    ("malicious", "악의적인", "형용사"),
    ("lofty", "높은, 고상한", "형용사"),
    ("replete", "가득 찬", "형용사"),
    ("credentials", "자격증", "명사"),
    ("demolish", "철거하다", "동사"),
    ("timely", "시기적절한", "형용사"),
    ("ambiance", "분위기", "명사"),
    ("impeachment", "탄핵", "명사"),
    ("stride", "큰 걸음", "명사"),
    ("vanguard", "선봉", "명사"),
    ("antiseptic", "방부제", "명사"),
    ("egalitarian", "평등주의적인", "형용사"),
    ("candidacy", "후보 지명", "명사"),
    ("fortified", "강화된", "형용사"),
    ("chronicle", "연대기", "명사"),
]

# ── 프롬프트 ───────────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a TEPS (Test of English Proficiency by Seoul National University) expert instructor.
Generate daily TEPS study content for a Korean learner.

STRICT RULES — follow exactly:
1. Use ONLY English alphabet and Korean Hangul characters. No Chinese characters, Hindi, Arabic, Japanese, IPA symbols, or any other scripts.
2. No emojis of any kind.
3. The reading passage MUST be written entirely in English. Never write the passage in Korean.
4. All explanations and translations use Korean only.
5. Follow the exact markdown format provided."""

USER_PROMPT_TEMPLATE = """Date: {date}

Today's 5 TEPS words (use EXACTLY these words — do not change them):
{word_list}

Write TEPS daily study content in the following format:

---

## 오늘의 TEPS 단어 (5개)

For each of the 5 words above, write:

**1. [word]** ([Korean pronunciation hint, e.g. 비질런트]) _{part of speech}_
- 뜻: [Korean meaning]
- 예문: [English example sentence showing the word in context]
- 해석: [Korean translation of the example sentence]

(Repeat for all 5 words)

---

## 단어 확인 퀴즈

Write 3 fill-in-the-blank questions using the 5 words above. Each question is a natural English sentence with a blank.

**Q1.** [English sentence with blank shown as ______]
(A) [option]  (B) [option]  (C) [option]  (D) [option]

**Q2.** [English sentence with blank shown as ______]
(A) [option]  (B) [option]  (C) [option]  (D) [option]

**Q3.** [English sentence with blank shown as ______]
(A) [option]  (B) [option]  (C) [option]  (D) [option]

<details>
<summary>퀴즈 정답 보기</summary>

Q1 정답: [(letter)] — [Korean explanation of why]

Q2 정답: [(letter)] — [Korean explanation of why]

Q3 정답: [(letter)] — [Korean explanation of why]

</details>

---

## 오늘의 독해

Write a 100-150 word English passage on a topic related to today's words (economics, society, science, or environment). TEPS reading difficulty level.

**지문:**
[English passage here — must be written entirely in English]

**문제 1.** [Question about the passage in English]
(A) [English option]
(B) [English option]
(C) [English option]
(D) [English option]

**문제 2.** [Question about the passage in English]
(A) [English option]
(B) [English option]
(C) [English option]
(D) [English option]

<details>
<summary>정답 및 해설 보기</summary>

**문제 1 정답:** [(letter)] — [Korean explanation]

**문제 2 정답:** [(letter)] — [Korean explanation]

**지문 해석:**
[Full Korean translation of the English passage. Use only Korean and English words here.]

</details>

---

## 오늘의 문법 포인트

**주제:** [Grammar topic in Korean]

[2-3 sentence Korean explanation of the grammar point]

**올바른 예문:**
- [Correct English sentence] — [Korean translation]

**틀린 예문과 수정:**
- 틀림: [Incorrect English sentence]
- 수정: [Correct English sentence] — [Korean explanation of the error]

---"""


def get_kst_date() -> datetime:
    return datetime.now(KST)


def pick_daily_words(date: datetime) -> list:
    """날짜를 시드로 사용해 매일 다른 5개 단어를 선택 (같은 날은 항상 동일)."""
    seed = int(date.strftime("%Y%m%d"))
    rng = random.Random(seed)
    return rng.sample(TEPS_VOCABULARY, 5)


def format_word_list(words: list) -> str:
    lines = []
    for i, (word, meaning, pos) in enumerate(words, 1):
        lines.append(f"{i}. {word} ({pos}) - {meaning}")
    return "\n".join(lines)


def generate_content(client: Groq, date_str: str, words: list) -> str:
    word_list = format_word_list(words)
    prompt = USER_PROMPT_TEMPLATE.format(date=date_str, word_list=word_list)

    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        temperature=0.7,
        max_tokens=2500,
    )

    return completion.choices[0].message.content


def build_front_matter(date: datetime, words: list) -> str:
    date_str = date.strftime("%Y-%m-%d")
    time_str = date.strftime("%Y-%m-%d %H:%M:%S +0900")
    word_tags = ", ".join(w[0] for w in words)

    return f"""---
layout: post
title: "TEPS 일일 학습 — {date_str}"
date: {time_str}
categories: teps
tags: [TEPS, 영어, {word_tags}]
---
"""


def save_post(content: str, date: datetime, words: list) -> str:
    os.makedirs(POSTS_DIR, exist_ok=True)

    date_str = date.strftime("%Y-%m-%d")
    filename = f"{date_str}-teps-daily.md"
    filepath = os.path.join(POSTS_DIR, filename)

    front_matter = build_front_matter(date, words)
    full_content = front_matter + "\n" + content

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(full_content)

    return filepath


def main():
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("Error: GROQ_API_KEY 환경변수가 설정되지 않았습니다.")
        sys.exit(1)

    client = Groq(api_key=api_key)
    today = get_kst_date()
    date_str = today.strftime("%Y년 %m월 %d일")

    words = pick_daily_words(today)
    word_names = ", ".join(w[0] for w in words)
    print(f"[{date_str}] 오늘의 단어: {word_names}")
    print("TEPS 포스트 생성 중...")

    try:
        content = generate_content(client, date_str, words)
        filepath = save_post(content, today, words)
        print(f"포스트 저장 완료: {filepath}")
    except Exception as e:
        print(f"포스트 생성 실패: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
